### ISSUE TITLE
No mode, owner, group specified in File['/etc/aptly.conf']

### ISSUE THREAD

**Issue by amosshapira** [gds-operations/puppet-aptly#26]
The File resource which defined /etc/aptly.conf ignores the $user parameter, making it impossible to execute the commands as any user but 'root' (the default user).

**Comment by rjw1** [comment]
What permissions does your aptly.conf file end up with?

**Comment by amosshapira** [comment]
```
# ls -l /etc/aptly.conf
-rw-r--r-- 1 root root 71 Jul  6 19:07 /etc/aptly.conf
```
This happens even when we set `$user = 'aptly'`

**Comment by ajlanghorn** [comment]
@amosshapira Can you paste the error you're getting in to this issue so that we can see it? It seems odd because your `/etc/aptly.conf` is world-readable, but only writable by root, which should work fine. The `aptly` user won't be able to write to that file, but it should be able to read.

**Comment by amosshapira** [comment]
@ajlanghorn looks like the report I passed wasn't complete. When I tried to re-create this on a different Vagrant box it passed fine, still with /etc/aptly.conf being owned by root but other files owned by a dedicated aptly user. I'll close this for now as it seems that the problem must be somewhere else.
