### ISSUE TITLE
Debian mirrors can need more than one key by repo

### ISSUE THREAD

**Issue by dw-thomast** [gds-operations/puppet-aptly#28]
Hi,

Some mirrors, like jessie, need 3 keys : 2B90D010, 46925553, 65FFB764. 
Today, it's impossible to give an array to the class (define) mirror.
So we used a workaround for adding all keys before loading the class aptly.
Is it possible to update your code for adding a array instead of a simple variable ?

Thomas

**Comment by mattbostock** [comment]
Hi @dw-thomast, this sounds like a feature we'd be interested in.

Would you be comfortable raising a PR to make this code change?

**Comment by dw-thomast** [comment]
The hard thing in this feature is that some mirrors can share the same keys >_<"
