### ISSUE TITLE
Support for puppetlabs-apt > 2.0

### ISSUE THREAD

**Issue by cintiadr** [gds-operations/puppet-aptly#34]
Currently, this module requires apt < 2.0

It would be nice to support newer versions of the module, I believe the only problem I could spot was the include_src in:
https://github.com/gds-operations/puppet-aptly/blob/master/manifests/init.pp#L68

**Comment by mattbostock** [comment]
Hi @cintiadr,

Thanks for the suggestion. We don't have any plans currently to upgrade to Apt 2.x, though we'd very much welcome a pull request to support it.

**Comment by cintiadr** [comment]
I can certainly do that. 

So the options are:
  - Change from include_src to include include => { 'src' =>  false}, making this module only compatible with >2.0
  - Simply remove include_src (the default in 2.0 is already false, and in 1.8 it won't hurt to have it)
  - Remove include_src and force apt module to be at least 2.0

Which one is the one you prefer? Or any other better solution?

**Comment by mattbostock** [comment]
@cintiadr I think we can remove support for puppetlabs-apt prior to 2.0, so removing `include_src` should be fine so long as we update our dependency in [metadata.json](https://github.com/gds-operations/puppet-aptly/blob/master/metadata.json).
