### ISSUE TITLE
Aptly API - RHEL6

### ISSUE THREAD

**Issue by eperdeme** [gds-operations/puppet-aptly#41]
Howdi,

Fringe case but the aptly::apiclass does not work on RHEL6 due to the following seems invalid sytax;
 
setuid <%= @user %>
setgid <%= @group %>

Also the command puppet then uses to start the service is '/sbin/service aptly-api start' and if it is upstart it neds to be "initctl start aptly-api". Might be best to use good  old style /etc/init.d? :)

**Comment by surminus** [comment]
Hi @eperdeme, 

Unfortunately RHEL6 is not one of our supported operating systems. We believe it would raise too many edge cases such as the issue you have described here.

Thanks,
Paul
