### ISSUE TITLE
apt dependency >2.0.0

### ISSUE THREAD

**Issue by ITler** [gds-operations/puppet-aptly#50]
Hy,

I'm using your 0.4.0 tag via forge... My problem is, that other modules in my puppet environment require `puppetlabs-apt` to be `>2.0.0`. So this leads to a conflict and I'm not able to use your module.

That's why I'd like to ask for a new release allowing `puppetlabs-apt` to be more current?

Kind regards
ITler

**Comment by alexmuller** [comment]
Hi ITler, #54 is open to release a new version and we'll get that pushed to the Forge. Thanks for opening this issue!

**Comment by alexmuller** [comment]
This should be on the Forge now! Please open issues or pull requests if you spot any problems.

**Comment by ITler** [comment]
Thanks Alex, I'll give it a try as soon as I can.
