### ISSUE TITLE
tab complete the init script

### ISSUE THREAD

**Issue by Lswith** [gds-operations/puppet-aptly#52]
could you change the aptly-api to be symlinked to init.d so that it can be tab completed?

**Comment by deanwilson** [comment]
This is something we'd rather not have in the core module. The `service` command will correctly tab complete files in `/etc/init.d/` and `/etc/init` and with the forthcoming Ubuntu move to systemd we'd rather keep this as simple as possible.

I'd suggest doing it in your own module.
