### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dhardy92** [gds-operations/puppet-aptly#84]
Hello, 
any chance for a new release soon on puppet forge ? (with the new gpg key)

Thank you

**Comment by elfranne** [comment]
Has been fixed in my PR #83 , waiting...

**Comment by martialblog** [comment]
Any update on this? Would be nice to get a new release in the forge.

**Comment by issyl0** [comment]
The puppet-aptly module v1.0.0 has been [released to Puppet Forge](https://forge.puppet.com/gdsoperations/aptly/), and we tagged a new release on GitHub with it. Thanks for your patience!
