### ISSUE TITLE
New APT key

### ISSUE THREAD

**Issue by basti-nis** [gds-operations/puppet-aptly#86]
Hi,

the old apt key doesn't work anymore.

Please use following code:
init.pp line 63
`
id     => '26DA9D8630302E0B86A7A2CBED75B5A4483DA07C',
`

**Comment by issyl0** [comment]
Hi @basti-nis, thanks for reporting this.

This issue was fixed in https://github.com/gds-operations/puppet-aptly/pull/83, and was released in v1.0.0 which is available [on the Puppet Forge](https://forge.puppet.com/gdsoperations/aptly).
